### PR TITLE
fix: ensure dragged photos are on top of other elements

### LINKED ISSUE #609: "Hold and drag photos" appears on top of dragged photo
It should appear behind the photo. Same for other elements, like the verification badges. When fiddling with z-indexes, extra testing should be done on Android.

### PR DESCRIPTION
**Pull request by sneed-dev**
Before this would look awkward, with other text in the same view like "Hold and drag photos" being rendered over the dragged image.

A zIndex of 999 seems arbitrary, but this was also used as a "really high value" in other places already.

Closes #609

---

To do:

- [x] Test in Android
- [x] Test in iOS

### CODE REVIEW

**Comment by sneed-dev** [comment]
https://github.com/user-attachments/assets/5c0d203a-eb86-44f8-8352-56a2c1a865ee

File: components/images/images.tsx [hunk 1]
```diff
@@ -1101,6 +1103,7 @@ const Images = ({
       style={{
         padding: 10,
         gap: 10,
+        ...style
```
Comment (sneed-dev) [inline components/images/images.tsx:1106]: Could've dumped the zIndex here directly, but figured it would make more sense to define this 1 level upwards as that's the container whose elements we're configuring indexes relative to.

File: components/images/images.tsx [hunk 2]
```diff
@@ -984,9 +984,11 @@ const SlotRow = ({
 };
 
 const Images = ({
-  input
+  input,
+  style,
 }: {
-  input: OptionGroupPhotos
+  input: OptionGroupPhotos,
+  style: object,
```
Comment (duogenesis) [inline components/images/images.tsx:991]: Before I run CI, I'm betting that the type checker will complain about about `style: object`. idk what the real type is meant to be. Some parameterized type with `View` in the name, maybe.

Comment (duogenesis) [reply components/images/images.tsx:991]: Nope! I was wrong

Comment (sneed-dev) [reply components/images/images.tsx:991]: Now that I think about it, it should probably be optional as well.

I'll see if I can find other instances where you pass style props downwards.

**Comment by duogenesis** [comment]
Thanks!
